/**
 * OpenAPI 3.1 document for the Factgraph API.
 *
 * The request schema is derived from the same Zod schema that validates
 * incoming requests (single source of truth — runtime validation and
 * published contract can't drift). Response shapes are described as
 * hand-written component schemas because we don't have Zod runtime
 * checks for them and don't need any (responses are server-built, not
 * untrusted input).
 *
 * The document is generated once at startup and served as-is from
 * `routes/openapi.ts`. Clients can:
 *
 *  - Download `/v1/factgraph/openapi.json` or `/v1/factgraph/openapi.yaml`
 *    and run `openapi-typescript`, `openapi-generator`, etc.
 *  - Visit `/v1/factgraph/docs` for an interactive Swagger UI rendering
 *    of the same spec.
 */
import {
  extendZodWithOpenApi,
  OpenAPIRegistry,
  OpenApiGeneratorV31,
} from '@asteasolutions/zod-to-openapi'
import { z } from 'zod'

import { QueryRequestSchema } from './routes/query.js'
import {
  HouseholdDeterminationRequestSchema,
  ExpeditedScreeningRequestSchema,
} from './translate/snap.js'

// Must run before any .openapi() call. Idempotent.
extendZodWithOpenApi(z)

export const API_VERSION = '0.1.0'

/**
 * Build a fresh OpenAPI document. Cheap to call but we cache it in the
 * route module so the spec serialization happens once per process.
 */
export function buildOpenApiDocument() {
  const registry = new OpenAPIRegistry()

  // -------------------------------------------------------------------------
  // Component schemas
  // -------------------------------------------------------------------------

  const QueryRequest = registry.register(
    'QueryRequest',
    QueryRequestSchema.openapi({
      description:
        'Evaluate one or more fact-graph nodes against partial input.',
    })
  )

  const ProblemDetails = registry.register(
    'ProblemDetails',
    z
      .object({
        type: z.string().url().openapi({
          description: 'A URI reference identifying the problem type.',
          example: 'https://tools.ietf.org/html/rfc9457',
        }),
        title: z.string().openapi({
          description: 'Short, human-readable summary of the problem type.',
          example: 'Invalid request body',
        }),
        status: z.number().int().openapi({
          description: 'HTTP status code generated by the origin server.',
          example: 400,
        }),
        detail: z.string().openapi({
          description:
            'Human-readable explanation specific to this occurrence.',
        }),
        errors: z
          .array(
            z.object({
              path: z.string().openapi({
                description:
                  'JSON path to the field that failed validation. Empty string for root-level errors.',
              }),
              message: z.string(),
            })
          )
          .optional()
          .openapi({
            description:
              'Present on 400 responses from request validation. Each entry pinpoints a specific failing field.',
          }),
      })
      .openapi({
        description: 'RFC 9457 Problem Details error response.',
      })
  )

  const PerMemberValue = registry.register(
    'PerMemberValue',
    z
      .array(
        z.object({
          memberId: z.string().openapi({
            description:
              "Caller-provided id from the entity row, or auto-generated `member-N` positional id when the caller didn't supply one.",
          }),
          value: z
            .unknown()
            .openapi({ description: 'The fact value for this member.' }),
        })
      )
      .openapi({
        description:
          "Per-member fact value. Returned for any target path that is collection-scoped (contains the collection wildcard segment). Each entry corresponds to one row from the request's `inputs[<collection-root>]` array.",
      })
  )

  const MissingInput = registry.register(
    'MissingInput',
    z
      .object({
        path: z.string().openapi({
          description: 'The fact-graph path the caller would need to supply.',
        }),
        name: z.string().openapi({
          description: 'Human-readable display name (from the rules XML).',
        }),
        description: z.string().optional().openapi({
          description: 'Free-form description of what this input represents.',
        }),
        dataType: z.string().openapi({
          description:
            'Writable type name from the fact graph (e.g. "Dollar", "Boolean", "Int", "Enum").',
          example: 'Dollar',
        }),
        enumOptions: z.array(z.string()).optional().openapi({
          description:
            'When dataType is "Enum" and the allowed values are statically resolvable, the list of accepted strings.',
        }),
      })
      .openapi({
        description:
          'One writable input the caller would need to supply to make a requested target resolvable. Deduped across all unresolved targets in the request.',
      })
  )

  const SupportingFact = registry.register(
    'SupportingFact',
    z
      .object({
        path: z.string(),
        name: z.string(),
        value: z.unknown().openapi({
          description:
            'Scalar value, or a PerMemberValue array for collection-scoped facts.',
        }),
      })
      .openapi({
        description:
          'One fact from the dependency tree of a queried target that resolved with the provided inputs. Only included when `include` contained `"supportingFacts"`.',
      })
  )

  // TraceCitation and TraceNode are response-only — never inbound, never
  // validated by Zod at runtime — so we register them as raw OpenAPI
  // component schemas. This sidesteps zod-to-openapi's lack of z.lazy()
  // support and lets TraceNode cleanly $ref itself for the recursive
  // children property.
  registry.registerComponent('schemas', 'TraceCitation', {
    type: 'object',
    description:
      "A policy citation resolved from the ruleset's references.json. Surfaced inline on trace nodes whose underlying fact has policy mappings.",
    required: ['sectionId', 'documentTitle'],
    properties: {
      sectionId: { type: 'string' },
      documentTitle: { type: 'string' },
      documentUrl: { type: 'string' },
      comment: { type: 'string' },
      page: { type: 'integer' },
    },
  })

  registry.registerComponent('schemas', 'TraceNode', {
    type: 'object',
    description:
      "One step in the explanation tree for a queried fact. The walker produces a recursive structure: the top-level node is the queried target; children are the operands or dependencies that contributed to its value. For boolean operators (All/Any) the walker visits every operand so the caller sees both the deciding branch and the alternatives — use `decisive` on each child to tell them apart. Arithmetic and Switch operators currently report the computed value but don't recurse — query those facts directly to drill in.",
    required: ['op', 'value', 'reason'],
    properties: {
      path: {
        type: 'string',
        description:
          'Fact path when this node corresponds to a model node. Anonymous sub-expressions omit this.',
      },
      name: { type: 'string' },
      description: { type: 'string' },
      op: {
        type: 'string',
        description:
          'Operator tag — All, Any, Not, GreaterThan, LessThanOrEqual, Dependency, Int, Dollar, True, False, Writable, Opaque, etc.',
      },
      value: {
        description: 'Computed value at this node, or null if unresolved.',
      },
      reason: {
        type: 'string',
        description:
          'One-sentence summary of how this value was decided. Safe to render directly in a caseworker UI.',
      },
      decisive: {
        type: 'boolean',
        description:
          "When this node appears inside its parent's `children` array, indicates whether it contributed to the parent's value. For an `All` that's false, only the first false child is decisive. For an `Any` that's true, only the first true child is. For `All`-true and `Any`-false every operand contributed equally and they all carry decisive=true. Always omitted on the root of a trace.",
      },
      children: {
        type: 'array',
        items: { $ref: '#/components/schemas/TraceNode' },
      },
      citations: {
        type: 'array',
        items: { $ref: '#/components/schemas/TraceCitation' },
      },
    },
  })

  registry.registerComponent('schemas', 'DecidingPathStep', {
    type: 'object',
    description:
      'One step in the deciding chain for a queried target. Path-bearing nodes only — anonymous sub-expressions are skipped in favor of the surrounding fact they live under.',
    required: ['path', 'value', 'op'],
    properties: {
      path: { type: 'string' },
      name: { type: 'string' },
      value: {},
      op: {
        type: 'string',
        description:
          'Operator at this point in the chain — useful for picking icons or color in a UI.',
      },
    },
  })

  registry.registerComponent('schemas', 'DecidingPath', {
    type: 'array',
    description:
      "Compact summary of the path-bearing nodes that drove a trace's outcome — [target, deciding child, …, deepest single-leaf cause]. Stops at the first branch point (All-true with multiple operands, Any-false where every operand failed) since beyond that the causation fans out and a flat list misrepresents it. The full trace is still available via `traces[<path>]` for callers that want to drill into branched chains.",
    items: { $ref: '#/components/schemas/DecidingPathStep' },
  })

  const DecidingPathRef = z.any().openapi('DecidingPath')

  // A Zod-side handle pointing at the TraceNode component we registered
  // above. Using `.openapi('TraceNode')` makes downstream consumers
  // (`QueryResponse.traces`) emit a $ref instead of inlining unknown.
  const TraceNode = z.any().openapi('TraceNode')

  const QueryResponse = registry.register(
    'QueryResponse',
    z
      .object({
        status: z.enum(['complete', 'incomplete']).openapi({
          description:
            '`complete` iff every requested target resolved. Otherwise `incomplete`.',
        }),
        rulesetVersion: z.string().openapi({
          description:
            'The ruleset id that was evaluated. Useful for clients that pin to a specific version (e.g. snap-fy2026 vs snap-fy2027).',
          example: 'snap-fy2026',
        }),
        values: z.record(z.string(), z.unknown()).openapi({
          description:
            "One entry per requested target. Value is `null` when the engine couldn't resolve that target with the provided inputs. Scalar facts return primitives; collection-scoped facts return PerMemberValue arrays.",
        }),
        metadata: z.unknown().optional().openapi({
          description:
            "Echoed unchanged from the request. Omitted if the request didn't send one.",
        }),
        missingInputs: z.array(MissingInput).optional().openapi({
          description:
            'Present iff status === "incomplete". Union of writables still needed across all unresolved targets, deduped by path.',
        }),
        supportingFacts: z.array(SupportingFact).optional().openapi({
          description:
            'Present iff request.include contained "supportingFacts". Every fact in the targets\' dependency trees that resolved.',
        }),
        traces: z.record(z.string(), TraceNode).optional().openapi({
          description:
            'Present iff request.include contained "trace". Keyed by target path; each entry is a recursive TraceNode tree explaining how that target\'s value was derived.',
        }),
        decidingPaths: z
          .record(z.string(), DecidingPathRef)
          .optional()
          .openapi({
            description:
              'Present iff request.include contained "trace". For each requested target, a compact ordered chain of path-bearing nodes from the target down to the deepest single-leaf cause. Powers one-line headline rendering — no need to walk the full TraceNode tree for the simple "this is why" sentence.',
          }),
      })
      .openapi({
        description:
          'Result of evaluating one or more fact-graph targets. Same shape regardless of complete vs incomplete; clients branch on status and on null values per target.',
      })
  )

  const RulesetSummary = registry.register(
    'RulesetSummary',
    z.object({
      id: z.string(),
      name: z.string(),
      format: z.enum(['factGraph']),
    })
  )

  // -------------------------------------------------------------------------
  // Eligibility adapter schemas (domain-oriented contract)
  // -------------------------------------------------------------------------

  const HouseholdDeterminationRequest = registry.register(
    'HouseholdDeterminationRequest',
    HouseholdDeterminationRequestSchema.openapi({
      description:
        'Final SNAP determination request for a household. Mirrors the blueprint eligibility-adapter contract (ORCA shape). `include: ["trace"]` is an adapter overlay that adds denial-reason and explanation detail to the response.',
    })
  )

  const ExpeditedScreeningRequest = registry.register(
    'ExpeditedScreeningRequest',
    ExpeditedScreeningRequestSchema.openapi({
      description:
        'Expedited SNAP screening request (7 CFR §273.2(i)). The base contract is household-only; this adapter accepts member/resource context via the overlay the contract sanctions, because the engine needs it to evaluate the criteria.',
    })
  )

  const ProgramDecision = registry.register(
    'ProgramDecision',
    z
      .object({
        metadata: z.record(z.string(), z.unknown()).openapi({
          description:
            'Echoed back unchanged from the request (adapter passthrough rule). The adapter never inspects this field.',
        }),
        program: z.string().openapi({ example: 'snap' }),
        status: z
          .enum(['pending', 'approved', 'denied', 'ineligible'])
          .openapi({
            description:
              'Eligibility outcome. `pending` here means the engine could not resolve eligibility because inputs were missing — the still-needed writables are surfaced on `x-missingInputs`.',
          }),
        path: z.enum(['auto', 'manual']).openapi({
          description:
            '`auto` — resolved by the rules engine with no caseworker in the loop.',
        }),
        denialReasonCode: z.string().optional().openapi({
          description:
            'Machine-readable reason code when status is denied/ineligible (e.g. FAILED_GROSS_INCOME_TEST).',
        }),
        'x-allotment': z.number().optional().openapi({
          description: 'Overlay: full-month SNAP allotment.',
        }),
        'x-proratedAllotment': z.number().optional().openapi({
          description: 'Overlay: prorated first-month allotment.',
        }),
        'x-expedited': z.boolean().optional().openapi({
          description:
            'Overlay: whether the household also qualifies for expedited processing.',
        }),
        'x-missingInputs': z.array(MissingInput).optional().openapi({
          description:
            'Overlay (progressive disclosure): present when status is `pending` because inputs were missing — the writables still needed to reach a determination. This is the structured missing-information hook the base contract lacks.',
        }),
        'x-translationNotes': z.array(z.string()).optional().openapi({
          description:
            'Overlay (transparency): assumptions the adapter made — disqualifier flags defaulted because the request did not carry them, or enum values that fell through to a default. The determination is conditional on these.',
        }),
        'x-decidingPath': z.unknown().optional().openapi({
          description:
            'Overlay: present when `include: ["trace"]` — the deciding chain (DecidingPath) for /eligibilityCategory.',
        }),
        'x-trace': z.unknown().optional().openapi({
          description:
            'Overlay: present when `include: ["trace"]` — the full explanation tree (TraceNode) for /eligibilityCategory.',
        }),
      })
      .openapi({
        description:
          "Eligibility decision for one program. The base fields (metadata, program, status, path, denialReasonCode) are the blueprint contract; `x-`-prefixed fields are this adapter's additive overlay (sanctioned by the contract's additionalProperties: true).",
      })
  )

  const ExpeditedScreeningResponse = registry.register(
    'ExpeditedScreeningResponse',
    z
      .object({
        metadata: z.record(z.string(), z.unknown()),
        expedited: z.boolean().openapi({
          description:
            'Whether the household qualifies for expedited SNAP processing.',
        }),
      })
      .openapi({ description: 'Response from expedited SNAP screening.' })
  )

  const MemberMedicaidDecision = registry.register(
    'MemberMedicaidDecision',
    z
      .object({
        memberId: z.string().openapi({
          description:
            "The household member this decision applies to (caller's member id).",
        }),
        status: z.enum(['pending', 'approved', 'denied', 'ineligible']),
        path: z.literal('auto'),
        denialReasonCode: z.string().optional(),
        'x-medicaidCategory': z.string().optional().openapi({
          description:
            'Infant | YoungChild | OlderChild | Adult | Pregnant | SsiRecipient | Ineligible.',
        }),
        'x-chpEligible': z.boolean().optional().openapi({
          description:
            "Whether the member qualifies for CHP+ (the children's plan) as an alternative.",
        }),
      })
      .openapi({ description: 'One member-level medicaid decision.' })
  )

  const MedicaidDeterminationResponse = registry.register(
    'MedicaidDeterminationResponse',
    z
      .object({
        metadata: z.record(z.string(), z.unknown()),
        program: z.literal('medicaid'),
        decisions: z.array(MemberMedicaidDecision).openapi({
          description:
            'One decision per household member. Medicaid is household-in / per-member-out: each member’s eligibility depends on the whole household (size + income → FPL%), so one household request yields N member decisions.',
        }),
        'x-missingInputs': z.array(MissingInput).optional(),
        'x-translationNotes': z.array(z.string()).optional(),
      })
      .openapi({
        description:
          "Medicaid determination result. Deliberately differs from the contract's per-applicant model: the request carries the whole household and the response returns a decision per member. See docs/contract-gap-analysis.md.",
      })
  )

  // -------------------------------------------------------------------------
  // Security scheme
  // -------------------------------------------------------------------------

  const bearerAuth = registry.registerComponent(
    'securitySchemes',
    'bearerAuth',
    {
      type: 'http',
      scheme: 'bearer',
      description:
        'Required on every /v1/* request when the deployed API has `API_BEARER_TOKEN` configured. Local dev runs without auth by default.',
    }
  )

  // -------------------------------------------------------------------------
  // Paths
  // -------------------------------------------------------------------------

  registry.registerPath({
    method: 'get',
    path: '/health',
    summary: 'Liveness probe.',
    description:
      'Unauthenticated. Returns `{"status":"ok"}` when the server is up. Used by deployment tooling.',
    tags: ['Meta'],
    responses: {
      200: {
        description: 'Server is up.',
        content: {
          'application/json': {
            schema: z.object({ status: z.literal('ok') }),
          },
        },
      },
    },
  })

  registry.registerPath({
    method: 'get',
    path: '/v1/factgraph/rulesets',
    summary: 'List every loaded ruleset.',
    description:
      'Use the `id` field of each entry as the `:rulesetId` URL parameter in subsequent calls.',
    tags: ['Discovery'],
    security: [{ [bearerAuth.name]: [] }],
    responses: {
      200: {
        description: 'List of rulesets.',
        content: {
          'application/json': {
            schema: z.object({ rulesets: z.array(RulesetSummary) }),
          },
        },
      },
      401: {
        description: 'Authentication required.',
        content: { 'application/json': { schema: ProblemDetails } },
      },
    },
  })

  registry.registerPath({
    method: 'get',
    path: '/v1/factgraph/{rulesetId}/schema',
    summary: 'Full node index for a ruleset.',
    description:
      'Returns every fact in the ruleset with its path, name, description, dependencies, data type, and (when mapped) policy citations. For day-one discovery prefer POST /query with no inputs — it returns only what is needed for a specific target.',
    tags: ['Discovery'],
    security: [{ [bearerAuth.name]: [] }],
    request: {
      params: z.object({
        rulesetId: z.string().openapi({ example: 'snap-fy2026' }),
      }),
    },
    responses: {
      200: {
        description: 'Ruleset model.',
        content: {
          'application/json': {
            schema: z
              .object({
                id: z.string(),
                name: z.string(),
                format: z.literal('factGraph'),
                nodes: z.record(z.string(), z.unknown()),
              })
              .openapi({
                description:
                  "Shape mirrors `rules-visualizer-shared-types`'s Model type. Each node carries its content, dependencies, and (optionally) references.",
              }),
          },
        },
      },
      401: {
        description: 'Authentication required.',
        content: { 'application/json': { schema: ProblemDetails } },
      },
      404: {
        description: 'Ruleset not found.',
        content: { 'application/json': { schema: ProblemDetails } },
      },
    },
  })

  registry.registerPath({
    method: 'post',
    path: '/v1/factgraph/{rulesetId}/query',
    summary: 'Evaluate one or more fact-graph targets.',
    description: [
      'Pass any subset of inputs (scalars and collection rows live in the same `inputs` map, keyed by fact path or collection root). The engine resolves what it can; the response carries values for resolved targets, and (when anything is missing) a deduped list of writables the caller would still need to supply.',
      '',
      'Targets can be top-level outputs (`/eligible`, `/snap`), intermediate gates (`/grossIncomeLimit`, `/meetsAssetTest`), or per-member facts. Per-member targets return arrays of `{memberId, value}` correlated to caller-provided `id` fields on entity rows.',
      '',
      'See the `examples-snap.md` doc in this repo for worked walkthroughs.',
    ].join('\n'),
    tags: ['Query'],
    security: [{ [bearerAuth.name]: [] }],
    request: {
      params: z.object({
        rulesetId: z.string().openapi({ example: 'snap-fy2026' }),
      }),
      body: {
        required: true,
        content: { 'application/json': { schema: QueryRequest } },
      },
    },
    responses: {
      200: {
        description:
          'Evaluation result. Always 200; `status` field discriminates complete vs incomplete.',
        content: { 'application/json': { schema: QueryResponse } },
      },
      400: {
        description:
          'Request body failed validation. The response includes both a human-readable `detail` string and a machine-readable `errors[]` array keyed by field path.',
        content: { 'application/json': { schema: ProblemDetails } },
      },
      401: {
        description: 'Authentication required.',
        content: { 'application/json': { schema: ProblemDetails } },
      },
      404: {
        description:
          'Ruleset or target not found. `detail` lists every bad path so the client can fix typos in one shot.',
        content: { 'application/json': { schema: ProblemDetails } },
      },
    },
  })

  registry.registerPath({
    method: 'post',
    path: '/v1/eligibility/evaluate/determination',
    summary: 'Final eligibility determination for one program.',
    description: [
      'Domain-oriented adapter endpoint conforming to the partner eligibility-adapter contract. Send an ORCA-shaped household request; receive a ProgramDecision. The caller never sees a Fact Graph path — all translation and defaulting is owned by the adapter.',
      '',
      'SNAP returns a single `ProgramDecision` for the household. Medicaid returns a `MedicaidDeterminationResponse` — one decision per member (household-in, per-member-out), a deliberate divergence from the contract’s per-applicant model (see docs/contract-gap-analysis.md). chip/tanf/ccdf return 501.',
      '',
      "Mounted at `/v1/eligibility` so a consumer can set its adapter base URL to `<host>/v1/eligibility` and reach the contract's bare `/evaluate/...` paths with no rewriting.",
    ].join('\n'),
    tags: ['Eligibility Adapter'],
    security: [{ [bearerAuth.name]: [] }],
    request: {
      body: {
        required: true,
        content: {
          'application/json': { schema: HouseholdDeterminationRequest },
        },
      },
    },
    responses: {
      200: {
        description:
          'Program decision. `ProgramDecision` for SNAP; `MedicaidDeterminationResponse` (per-member) for Medicaid.',
        content: {
          'application/json': {
            schema: z.union([ProgramDecision, MedicaidDeterminationResponse]),
          },
        },
      },
      400: {
        description: 'Invalid or unknown-program request.',
        content: { 'application/json': { schema: ProblemDetails } },
      },
      401: {
        description: 'Authentication required.',
        content: { 'application/json': { schema: ProblemDetails } },
      },
      501: {
        description:
          'Program recognized but not yet implemented by this adapter.',
        content: { 'application/json': { schema: ProblemDetails } },
      },
    },
  })

  registry.registerPath({
    method: 'post',
    path: '/v1/eligibility/evaluate/expedited-screening',
    summary: 'Expedited SNAP screening.',
    description:
      "Evaluates whether a household qualifies for expedited SNAP processing under 7 CFR §273.2(i). Returns the contract's ExpeditedScreeningResponse.",
    tags: ['Eligibility Adapter'],
    security: [{ [bearerAuth.name]: [] }],
    request: {
      body: {
        required: true,
        content: { 'application/json': { schema: ExpeditedScreeningRequest } },
      },
    },
    responses: {
      200: {
        description: 'Expedited screening result.',
        content: { 'application/json': { schema: ExpeditedScreeningResponse } },
      },
      400: {
        description: 'Invalid request.',
        content: { 'application/json': { schema: ProblemDetails } },
      },
      401: {
        description: 'Authentication required.',
        content: { 'application/json': { schema: ProblemDetails } },
      },
    },
  })

  registry.registerPath({
    method: 'post',
    path: '/v1/eligibility/evaluate/medicaid-ex-parte',
    summary: 'Medicaid ex parte evaluation (not yet supported).',
    description:
      'Reserved by the eligibility-adapter contract. Not yet implemented by this adapter — the flow depends on electronic data-exchange results (FDSH FTI, Medicare/VCI) that are not yet modeled. Returns 501.',
    tags: ['Eligibility Adapter'],
    security: [{ [bearerAuth.name]: [] }],
    responses: {
      501: {
        description: 'Not implemented.',
        content: { 'application/json': { schema: ProblemDetails } },
      },
    },
  })

  // -------------------------------------------------------------------------
  // Generate
  // -------------------------------------------------------------------------

  const generator = new OpenApiGeneratorV31(registry.definitions)
  return generator.generateDocument({
    openapi: '3.1.0',
    info: {
      title: 'Factgraph API',
      version: API_VERSION,
      description: [
        'A generic HTTP adapter for Fact Graph rulesets defined in this repository.',
        '',
        'One endpoint shape (`POST /v1/factgraph/{rulesetId}/query`) handles every kind of query: top-level outputs, intermediate gates, per-member facts, partial input, full determinations. Multiple targets per call.',
        '',
        'When inputs are missing, the response includes a precise list of what is still needed — letting partner UIs drive intake forms dynamically from the rules rather than maintaining a parallel schema.',
        '',
        'See the [partner-facing docs](https://github.com/Gary-Community-Ventures/rules-visualizer/tree/main/packages/factgraph-api) for concepts, worked SNAP examples, and the changelog.',
      ].join('\n'),
      license: { name: 'MPL-2.0' },
    },
    servers: [
      {
        url: 'https://rules-visualizer-factgraph-api-f0c14673cf3a.herokuapp.com',
        description: 'Production deploy',
      },
      {
        url: 'http://localhost:5002',
        description: 'Local dev server',
      },
    ],
    tags: [
      { name: 'Meta', description: 'Liveness probes and health checks.' },
      {
        name: 'Discovery',
        description: 'Find available rulesets and inspect their schema.',
      },
      {
        name: 'Query',
        description:
          'Evaluate fact-graph targets against caller-provided input.',
      },
      {
        name: 'Eligibility Adapter',
        description:
          'Domain-oriented endpoints conforming to the partner eligibility-adapter contract. Request/response are shaped around the business workflow (ORCA model); Fact Graph paths are never exposed.',
      },
    ],
  })
}
